In [1]:
import numpy as np

In [2]:
np.__version__

'2.1.3'

In [3]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [6]:
print(type(my_list))

<class 'list'>


In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [11]:
np. #217 functionalities are there(numpy is complete) 

SyntaxError: invalid syntax (1548039472.py, line 1)

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [14]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [16]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [17]:
np.arange(10,5)

array([], dtype=int64)

In [18]:
np.arange(-10,5)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4])

In [19]:
np.arange(0,100,5,3)

TypeError: Cannot interpret '3' as a data type

In [20]:
np.zeros(3) # parameter tunnning 

array([0., 0., 0.])

In [21]:
np.zeros(3 ,dtype=int) #hyperparamenter 

array([0, 0, 0])

In [23]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [24]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [25]:
np.zeros((5,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [26]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
np.ones((2,6) ,dtype=int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [28]:
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [29]:
random.rand(2,3)

NameError: name 'random' is not defined

In [32]:
np.random.rand(2,3)

array([[0.05656365, 0.14616306, 0.92428808],
       [0.94900201, 0.33258852, 0.40293771]])

In [33]:
np.random.randint(4,6)

4

In [34]:
np.random.randint(4,10)

5

In [35]:
np.random.randint(1,20,4)

array([10,  9,  9,  1], dtype=int32)

In [38]:
a = np.random.randint(10,40,(10,10))
print(a.dtype)

int32


In [39]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [42]:
np.arange(1,17).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [43]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [ ]:
np.arange.()